---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpuexecutioncap: 90
    cpus: 1
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.0
#  - name: ubuntu-15.04

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[ndb::install]
      - recipe[ndb::mgmd]
      - recipe[ndb::ndbd]
      - recipe[ndb::mysqld]
      - recipe[elastic::default]
      - recipe[hopsmonitor::install]
      - recipe[hopsmonitor::default]
    attributes:
         kagent:
            dir: '/srv/hops'
            user: 'glassfish'
            group: 'glassfish'
            default:
                private_ips: ["10.0.2.15"]
         ndb:
            user: mysql
            group: mysql
            dir: "/srv/hops"
            DataMemory: "111"
            mgmd:
               private_ips: ["10.0.2.15"]
            ndbd:
               private_ips: ["10.0.2.15"]
            mysqld:
               private_ips: ["10.0.2.15"]
         hopsmonitor:
            dir: '/srv/hops'
            user: 'glassfish'
            group: 'glassfish'
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         elastic:
            dir: '/srv/hops' 
            user: 'glassfish'
            group: 'glassfish'
            default:
                private_ips: ["10.0.2.15"]
         grafana:
            default:
                private_ips: ["10.0.2.15"]
         influxdb:
            default:
                private_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "true"
